metodo que devuelve un booleano si el numero es amstrong o no.
Mel-Gr/DAW-Entornos-P10-Carol pull request #30
Opened 2023-03-22 02:02 UTC by 0T4KU1312

2023-03-22 12:45 UTC, Mel-Gr requested changes
Por favor, cambiálo para que funcione para cualquier número de cifras

2023-03-22 12:45 UTC, Mel-Gr commented on src/main/java/ieseuropa/Numero.java
> +	        suma += Math.pow(digito, 3);
El método así sólo funciona para los números de tres cifras, pero los de 4 o 5 o más tambien pueden ser números de Armstrong

2023-03-22 15:49 UTC, 0T4KU1312 commented on src/main/java/ieseuropa/Numero.java
> +	        suma += Math.pow(digito, 3);
vale entiendo ahora me pongo.

2023-03-23 03:57 UTC, 0T4KU1312 commented on src/main/java/ieseuropa/Numero.java
> +	        suma += Math.pow(digito, 3);
creo que ya estaría para hacer el merge con dev revísalo por si acaso!

2023-03-23 16:02 UTC, Mel-Gr approved these changes

2023-03-23 16:04 UTC, merged